apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: promotheous-app
spec:
  ports:
    - port: 9090
  selector:
    app: promotheous-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotheous-app
spec:
  selector:
    matchLabels:
      app: promotheous-app
  template:
    metadata:
      labels:
        app: promotheous-app
    spec:
      containers:
      - name: promotheous-con
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        -  name: prometheus-config
           mountPath: /etc/prometheus/prometheus.yml
           subPath: prometheus.yml 
        -  name: promo-storage
           mountPath: /prometheus 
      volumes:
      -  name: prometheus-config
         configMap:
              name: prometheus-config
      -  name: promo-storage
         persistentVolumeClaim:
              claimName: promo-storage
           

